
server:
  port: 8881
spring:
  application:
    name: service-feign
  zipkin:
    base-url: http://localhost:10000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

feign.hystrix.enabled: true






