server:
  port: 8888

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false  #通过置为false来表明自己是一个eureka server.
    fetchRegistry: false

    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#     通过访问http://localhost:8888/ 可以观察服务注册情况


#spring:
#  profiles:
#    active: peer1
#
#eureka.instance.preferIpAddress: true