server:
  port: 8888

eureka:
  instance:
    hostname: localhost
  client:
#    \u8868\u660E\u81EA\u5DF1\u662F\u4E00\u4E2Aeureka server
    registerWithEureka: false
    fetchRegistry: false

    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


#spring:
#  profiles:
#    active: peer1
#
#eureka.instance.preferIpAddress: true