eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
spring.application.name: config-server

server:
  port: 9999
spring:
  cloud:
    config:
      server:
        git:  # 如果git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写，本例子是公开仓库，放心使用。
          #远程仓库https://github.com/forezp/SpringcloudConfig/中在respo文件夹下有名为config-client-dev.properties的文件，
          #其中包含有一个属性：golden = 小星星， 可以启动程序：访问http://localhost:9999/foo/dev
          uri: https://github.com/zhao520a1a/SpringCloudDemo.git
          searchPaths: testConfigByGit
          username:
          password:
      label: master   #配置仓库的分支


