spring:
  application.name: service-turbine
server:
  port: 11111

security.basic.enabled: false
turbine:
  aggregator:
      clusterConfig: default   # 指定聚合哪些集群，多个使用","分割，默认为default。可使用http://.../turbine.stream?cluster={clusterConfig之一}访问
  appConfig: service-ribbon,service-feign  # 配置Eureka中的serviceId列表，表明监控哪些服务
  clusterNameExpression: new String("default")
   # 1. clusterNameExpression指定集群名称，默认表达式appName；此时：turbine.aggregator.clusterConfig需要配置想要监控的应用名称
   # 2. 当clusterNameExpression: default时，turbine.aggregator.clusterConfig可以不写，因为默认就是default
   # 3. 当clusterNameExpression: metadata['cluster']时，假设想要监控的集群ABC
   # 应用中应配置 eureka.instance.metadata-map.cluster: ABC，还需要配置turbine.aggregator.clusterConfig: ABC
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
